pipeline
{
agent any
stages {
    stage ('build') 
    {
        steps {
            echo "This is build stage"
        }

    }

    stage ('test')
    {
        steps {
            echo "Thies is test stage"
        }
    }
        stage ('deploy')
    {
        steps {
            echo "Thies is deploy stage"
        }
    }
}
}